### ISSUE TITLE
Request: Disenchant / Upgrade Eternals set shards

### ISSUE THREAD

**Issue by DelVision** [MaciejGorczyca/HextechButBetter#15]
The request is relatively straight forward and is basically already on the title..

All I want to do is to get rid of the eternals set shards with one click.. 

And obviously option to update them like any other shards would be nice for those who need it.

**Comment by MaciejGorczyca** [comment]
Added ETERNALS type, disenchanting works, upgrading not sure. Upgrading some stuff didn't work for me in past for some things so idk if it does work for eternals.
