### ISSUE TITLE
Doesnt work on SEA region accounts.

### ISSUE THREAD

**Issue by chavan0** [MaciejGorczyca/HextechButBetter#16]
"It says not connected to league client. You need to login first". I think since the last commit is in 2022 and the SEA region being released in 2023 it doesnt recognize the client.

**Comment by Doubleoh9inches** [comment]
Mine works, well at least shows me the collections, in the Philippines PH2. I haven't used the tool to perform any actions yet but I will update when I do.

**Comment by MaciejGorczyca** [comment]
> "It says not connected to league client. You need to login first". I think since the last commit is in 2022 and the SEA region being released in 2023 it doesnt recognize the client.

It should work as long as the region uses Riot official client. If it says not connected then most likely you need to re-run as admin (no rights to interact with client).

If something still doesn't work then lemme know or open new issue.
