### ISSUE TITLE
Suggestion: Total Counts

### ISSUE THREAD

**Issue by Maarslet** [MaciejGorczyca/HextechButBetter#2]
Hey, not sure where to leave suggestions so I'll do it here for now.

I suggest adding a total count to the amount of Champion Shards, Skin Shards, Emotes, etc somewhere in the GUI. It makes it much easier to get an overview when you have hundreds if not more shards.

**Comment by MaciejGorczyca** [comment]
Implemented some time ago, probably in 1.4.
