### ISSUE TITLE
Bulk disenchant doesn't get all

### ISSUE THREAD

**Issue by djinnerator** [MaciejGorczyca/HextechButBetter#3]
I just did about 90-ish champ shards. Amazing tool, so much better than manually doing it. The problem I ran into was After putting all the shard count in, it skipped about 9 different champs or didn't completely disenchant it. Had to run it a second time.

Also a suggestion maybe: add a function that would load all the shards at once. For example, each champion shard starts at count 0 and the program shows the total count per champ. I just did "tab > 9 > tab > 9" repeatedly, since it automatically brings it down to the max value. It'd be really great to be able to not have to do that.

Thanks for the work on this btw! I wish Riot would've implemented this a long time ago.

**Comment by MaciejGorczyca** [comment]
I think I did some logic (maybe in 1.4 or 1.3) that repeats the disenchanting if it failed but I'm not sure how reliable is that.

I just updated the tool to automatically set the textbox value to the number of shards owned so you don't have to set them all to `9` then `TAB` over and over. Just make sure you set `0` to the textbox next to the champ you want to save.
